# Choose whatever you want, version >= 1.16
FROM golang:1.20-alpine

WORKDIR /app

RUN go install github.com/cosmtrek/air@latest

COPY go.mod go.sum pkg air/order-detail.air.toml internal/order_details cmd/order_details ./
RUN go mod download

CMD ["air", "-c", "order-detail.air.toml"]
